
language: php

php: 7

git:
  depth: 8

# before_install: nvm install v8

install: composer install

before_script:
  - composer validate
  - composer ci-install
  - composer write-ignore-xml

script: composer test

# End.
